name: Deploy to Sakura Rental Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Sakura Rental Server
      env:
        SAKURA_PRIVATE_KEY: ${{ secrets.SAKURA_PRIVATE_KEY }}
        SAKURA_HOST: ${{ secrets.SAKURA_HOST }}
        SAKURA_USER: ${{ secrets.SAKURA_USER }}
      run: |
        echo "$SAKURA_PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${SAKURA_USER}@${SAKURA_HOST} '
          cd /home/castero/laravel11-test &&
          git pull origin main &&
          composer install --no-dev &&
          php artisan migrate --force
        '
