name: Deploy to Sakura Rental Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Sakura Rental Server
      env:
        SAKURA_PRIVATE_KEY_BASE64: ${{ secrets.SAKURA_PRIVATE_KEY_BASE64 }}
        SAKURA_HOST: ${{ secrets.SAKURA_HOST }}
        SAKURA_USER: ${{ secrets.SAKURA_USER }}
      run: |
        echo "$SAKURA_PRIVATE_KEY_BASE64" | base64 --decode > private_key && chmod 600 private_key
        cat private_key
        ssh -v -o StrictHostKeyChecking=no -i private_key ${SAKURA_USER}@${SAKURA_HOST} '
          cd /home/***/laravel11-test &&
          git pull origin main &&
          composer install --no-dev &&
          php artisan migrate --force
        '
    - name: Check private_key content
      run: cat private_key
    - name: Check private_key file type
      run: file private_key
